version: '3'
services:
  db:
    image: postgres
    # volumes:
      # - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    image: registry.cn-beijing.aliyuncs.com/codeorder/codeorder-official-network
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # volumes:
      # - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db